### ISSUE TITLE
ts 类型“NodeModule”上不存在属性“hot”。

### ISSUE THREAD

**Issue by cyrus123456** [guansss/webpack-monkey#1]
![image](https://github.com/guansss/webpack-monkey/assets/73327722/7952c41a-464e-4713-b976-6771de353028)

**Comment by guansss** [comment]
参考这个文件 https://github.com/guansss/webpack-monkey/blob/main/examples/ts-hello-world/src/env.d.ts

或者在你的某个 ts 文件里加一行 `import "webpack/module"`
